# Generated by Django 3.1.1 on 2020-12-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Education', max_length=225),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Title tag is for to be displayed instead of title', max_length=225),
        ),
    ]
